const mappingDetails = {
  data: {
    rooms: [
      {
        id: 651942002,
        title: "Single Room",
        max_children: null,
        rates: [
          {
            id: 18527581,
            title: "standard rate",
            readonly: false,
            occupancies: [],
            pricing: "Standard",
            max_persons: 1,
            price_1: false,
            parent_rate_id: "",
          },
          {
            id: 18527582,
            title: "special rate",
            readonly: false,
            occupancies: [],
            pricing: "Standard",
            max_persons: 1,
            price_1: false,
            parent_rate_id: "",
          },
          {
            id: 18527583,
            title: "non-refundable rate",
            readonly: false,
            occupancies: [],
            pricing: "Standard",
            max_persons: 1,
            price_1: false,
            parent_rate_id: "",
          },
        ],
      },
      {
        id: 651942003,
        title: "Double Room",
        max_children: null,
        rates: [
          {
            id: 18527581,
            title: "standard rate",
            readonly: false,
            occupancies: [],
            pricing: "Standard",
            max_persons: 2,
            price_1: false,
            parent_rate_id: "",
          },
          {
            id: 18527582,
            title: "special rate",
            readonly: false,
            occupancies: [],
            pricing: "Standard",
            max_persons: 2,
            price_1: false,
            parent_rate_id: "",
          },
          {
            id: 18527583,
            title: "non-refundable rate",
            readonly: false,
            occupancies: [],
            pricing: "Standard",
            max_persons: 2,
            price_1: false,
            parent_rate_id: "",
          },
        ],
      },
      {
        id: 651942004,
        title: "Suite",
        max_children: null,
        rates: [
          {
            id: 18527581,
            title: "standard rate",
            readonly: false,
            occupancies: [],
            pricing: "Standard",
            max_persons: 3,
            price_1: false,
            parent_rate_id: "",
          },
          {
            id: 18527582,
            title: "special rate",
            readonly: false,
            occupancies: [],
            pricing: "Standard",
            max_persons: 3,
            price_1: false,
            parent_rate_id: "",
          },
          {
            id: 18527583,
            title: "non-refundable rate",
            readonly: false,
            occupancies: [],
            pricing: "Standard",
            max_persons: 3,
            price_1: false,
            parent_rate_id: "",
          },
        ],
      },
    ],
    pricing_type: "Standard",
  },
};

export default mappingDetails;
export { mappingDetails };
